### ISSUE TITLE
Why not replace /{SOME_FOLDER} with /directory-listing?

### ISSUE THREAD

**Issue by UltimateByte** [ramlmn/Apache-Directory-Listing#1]
Hi,

Title says it all, would require less edit from users and make it more usable.
 Just discovered your project, I have to say it's a bit discouraging :)

**Comment by r0mflip** [comment]
Sorry for getting to you late. This project, currently, is not quite expected to be active. Those decisions were made long back and this repo is to be archived soon. If you want to use it anyway please fork it and use accordingly. Thanks.

**Comment by notlmn** [comment]
@UltimateByte Basically the reason is to make the user work a bit more on making sure that they are not lazy enough to let the directory name be `directory-listing`, ideally we want you to change the name to something else.

😈
