### ISSUE TITLE
Very gooooooood!

### ISSUE THREAD

**Issue by itcools** [ramlmn/Apache-Directory-Listing#9]
Hello

It looks really good after applying it.

But what should I do if I want it to be applied to the subdirectory?

If possible, it would be nice if you could explain it to beginners as easily as possible.

**Comment by p-cauty** [comment]
Hi! Try this: https://github.com/ramlmn/Apache-Directory-Listing/issues/10#issuecomment-955602821

**Comment by notlmn** [comment]
Thanks @phpitou

Same as https://github.com/ramlmn/Apache-Directory-Listing/issues/10#issuecomment-955666662
